services:
  - type: web
    name: hassaan-job-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
    autoDeploy: true
